'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FlashBooking

    Partial Public Class Booking
        Public Property Id As Integer
        Public Property CreationDate As Date
        Public Property CheckInDateTime As Date
        Public Property CheckOutDateTime As Date
        Public Property IsConfirmed As Boolean = false
    
        Public Overridable Property Guest As Guest
        Public Overridable Property Room As Room
    
    End Class

End Namespace
