'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FlashBooking

    Partial Public Class GuestType
        Public Property Id As Integer
        Public Property Name As String
        Public Property Description As String
        Public Property Cost As Decimal
    
        Public Overridable Property Guests As ICollection(Of Guest) = New HashSet(Of Guest)
    
    End Class

End Namespace
