'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FlashBooking

    Partial Public Class Guest
        Public Property Id As Integer
        Public Property Name As String
        Public Property LastName As String
        Public Property PhoneNumber As String
        Public Property City As String
        Public Property Country As String
        Public Property GuestTypeId As Integer
        Public Property BirthDate As Nullable(Of Date)
    
        Public Overridable Property Booking As Booking
        Public Overridable Property GuestType As GuestType
    
    End Class

End Namespace
