'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FlashBooking

    Partial Public Class Room
        Public Property Id As Integer
        Public Property Description As String
        Public Property RoomTypeId As Integer
    
        Public Overridable Property Booking As ICollection(Of Booking) = New HashSet(Of Booking)
        Public Overridable Property RoomType As RoomType
    
    End Class

End Namespace
