'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace FlashBooking

    Partial Public Class RoomType
        Public Property Id As Integer
        Public Property Name As String
        Public Property Description As String
        Public Property AdultsCapacity As Integer = 2
        Public Property ChildrenCapacity As Single
        Public Property TotalCapacity As Integer
    
        Public Overridable Property Rooms As ICollection(Of Room) = New HashSet(Of Room)
    
    End Class

End Namespace
